### ISSUE TITLE
Might be me but it doesn't want to install.

### ISSUE THREAD

**Issue by StealthChicken** [PiBrewing/cbpi4-DependentActor#1]
Plugin won't install.
Try both ways.

pi@raspberrypi:~ $ sudo pip3 install cbpi4-DependentActor
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement cbpi4-DependentActor
ERROR: No matching distribution found for cbpi4-DependentActor

pi@raspberrypi:~ $ sudo pip3 install https://github.com/avollkopf/cbpi4-DependentActor.git
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/avollkopf/cbpi4-DependentActor.git
  Downloading https://github.com/avollkopf/cbpi4-DependentActor.git
     | 178 kB 695 kB/s
  ERROR: Cannot unpack file /tmp/pip-unpack-0tnc6x68/cbpi4-DependentActor.git (downloaded from /tmp/pip-req-build-0oqpm9g4, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-0oqpm9g4

**Comment by avollkopf** [comment]
You are trying to install the plugin with it's name via pypi. However, the plugin is not available on pypi as package. You need to install it from the repo directly as described in examples in the documentation -> https://openbrewing.gitbook.io/craftbeerpi4_support/readme/plugin-installation
